### ISSUE TITLE
Can not connect to the created kernel

### ISSUE THREAD

**Issue by HuangYiran** [hpcraink/workshop-parallel-jupyter#1]
Hello everyone,

I try to create a new kernel named 'work' and add it to the jupyter notebook. I can see the kernel in the notebook now, however I can not connect to it. 
<img width="1262" alt="Screenshot 2021-11-17 at 15 01 26" src="https://user-images.githubusercontent.com/25362934/142214812-e48ae4fb-d3d7-403c-b15a-4e382d6f5059.png">
after I select the 'work' kernel, it turns out to be disconnect (no kernel):
<img width="1272" alt="Screenshot 2021-11-17 at 15 02 23" src="https://user-images.githubusercontent.com/25362934/142215012-fcbdeb82-d0bf-41bb-a46f-16ed26cd9e3c.png">
I try to list all the installed kernel in the command line, and  the 'work' kernel is also there:
<img width="894" alt="Screenshot 2021-11-17 at 15 04 11" src="https://user-images.githubusercontent.com/25362934/142215281-9d544055-9567-48c9-bdff-ec9656f3cd66.png">
here is how the kernel.json file in the directory look like:
<img width="529" alt="Screenshot 2021-11-17 at 15 05 15" src="https://user-images.githubusercontent.com/25362934/142215465-90b34a77-6946-477d-816e-084efc62e1fc.png">
I also tried the other two kernels in the list. Only the default kernel works good.

am I missing something? thank you for the help in advance.

best
@julianruess

**Comment by juru1234** [comment]
Hi,

you have to click on the blue hexagon on the left and unload the 
"jupyter/base" or "jupyter/tensorflow" module before you can connect to 
your own kernel.

Regards
Julian

Am 2021-11-17 15:11, schrieb Yiran Huang:

**Comment by HuangYiran** [comment]
Hi, 
thanks for the fast reply. 
The above attempts were made under the jupyter/base module. I convert to the jupyter/tensorflow module today and the results did not change: no kernel.
<img width="1247" alt="Screenshot 2021-11-18 at 10 45 19" src="https://user-images.githubusercontent.com/25362934/142391098-45ec017a-823e-43ff-afa7-0a07445bacc9.png">

best

**Comment by juru1234** [comment]
Hi,

you have to unload jupyter/base and jupyter/tensorflow.

No module should be loaded.

Regards
Julian

Am 2021-11-18 10:46, schrieb Yiran Huang:

**Comment by HuangYiran** [comment]
it works, thank you. Sorry that I misread the reply.
